Parsing error near 'Caracteristica: Inventario'
Parsing error near 'In order to avoid silly mistakes'
Parsing error near 'As a math idiot'
Parsing error near 'I want to be told the sum of two numbers'
Parsing error near 'Scenario: Add two numbers'
Parsing error near 'Given I have entered 50 into the calculator'