Parsing error near '@language es'
Parsing error near 'Característica: Soluciones sin nuilds'
Parsing error near 'In order to avoid silly mistakes'
Parsing error near 'As a math idiot'
Parsing error near 'I want to be told the sum of two numbers'
Parsing error near 'Escenario: Add two numbers'